#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Source Zplug.
source "${ZPLUG_HOME}/init.zsh"

# Source custom files
for ZSH_FILE in "${ZDOTDIR:-$HOME}"/zsh.d/*.zsh(N); do
	source "${ZSH_FILE}"
done

# Functions
export fpath=($ZDOTDIR/functions $fpath)

# General Functions
zsource()
{
  emulate -L zsh
  echo Loading "${ZDOTDIR:-$HOME}"/.zshrc
  source "${ZDOTDIR:-$HOME}"/.zshrc
}
